name: "Terraform"

on:
  push:
    branches:
      - main

jobs:
  checkout:
    name: Checkout code
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  configureAWS:
    name: Configure AWS Credentials
    needs: [checkout]
    runs-on: self-hosted
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          aws-session-token:  ${{ secrets.AWS_SESSION_TOKEN }}

  terraform-format:
    name: Terraform Format
    needs: [checkout,configureAWS]
    runs-on: self-hosted
    defaults:
      run:
        working-directory: src
    steps:
      - name: Terraform Format
        id: fmt
        run: terraform fmt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          aws-session-token:  ${{ secrets.AWS_SESSION_TOKEN }}


  terraform-init:
    name: Terraform Init
    needs: [terraform-format]
    runs-on: self-hosted
    defaults:
      run:
        working-directory: src
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          aws-session-token:  ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Save Terraform state
        id: save_state
        uses: actions/upload-artifact@v3
        with:
          name: terraform-state
          path: src/.terraform

  terraform-plan:
    name: Terraform Plan
    needs: [terraform-init]
    runs-on: self-hosted
    defaults:
      run:
        working-directory: src
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          aws-session-token:  ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Restore Terraform state
        uses: actions/download-artifact@v3
        with:
          name: terraform-state
          path: src/.terraform

      - name: Terraform Plan
        id: plan
        run: terraform plan

  terraform-apply:
    name: Terraform Apply
    needs: [terraform-plan]
    runs-on: self-hosted
    defaults:
      run:
        working-directory: src
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          aws-session-token:  ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Restore Terraform state
        uses: actions/download-artifact@v3
        with:
          name: terraform-state
          path: src/.terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve